apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
spec:
  source:
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 1.49.2
    path: stable/kubecost
    helm:
      valueFiles:
        - values.yaml
